[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://book.ruby-salon.com/*"
  to = "https://ruby-salon.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Caching policy for static assets to improve performance for repeat visitors
[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-critical-css"