[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://book.ruby-salon.com/*"
  to = "https://ruby-salon.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200